In [1]:
import numpy as np

# N维数组对象ndarray  
**ndarray在程序中的别名是:array  
<font color="red">np.array()</font>生成一个ndarray数组**

In [2]:
a = np.array([[0,1,2,3,4],
              [9,8,7,6,5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

**np.array()输出成[ ]形式，元素由空格分割**

In [3]:
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


**ndarray数组的属性**

In [4]:
a.ndim

2

In [5]:
a.shape

(2, 5)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

In [9]:
x = np.array([[0,1,2,3,4],
              [9,8,7,6]],dtype=object)

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.itemsize

8

# ndarray数组的创建方法  
**从列表类型创建**

In [13]:
x = np.array([0,1,2,3])
print(x)

[0 1 2 3]


**从元组类型创建**

In [14]:
x = np.array((0,1,2,3))
print(x)

[0 1 2 3]


**从列表和元组混合类型创建**

In [15]:
x = np.array([[1,2],[9,8],(0.1,0.2)])
print(x)

[[1.  2. ]
 [9.  8. ]
 [0.1 0.2]]


**使用Numpy中的函数创建**

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
x = np.ones((2,3,4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [21]:
x.shape

(2, 3, 4)

In [22]:
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [23]:
b = np.linspace(1,10,4,endpoint=False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [24]:
c = np.concatenate((a,b))
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

# ndarray数组的变换  

In [25]:
a = np.ones((2,3,4), dtype=np.int32)
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [26]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [27]:
a.resize((3,8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [28]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [29]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
b = a.flatten()
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [31]:
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

**ndarray数组向列表的转换**

In [32]:
a = np.full((2,3,4),25,dtype = np.int32)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [33]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

# ndarray数组的操作  
**一维数组的索引和切片**

In [34]:
a = np.array([9,8,7,6,5])
a[2]

7

In [35]:
a[1:4:2]

array([8, 6])

**多维数组的索引和切片**

In [36]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
a[1,2,3]

23

In [38]:
a[0,1,2]

6

In [39]:
a[-1,-2,-3]

17

In [40]:
a[0,0,:2]

array([0, 1])

# ndarray数组的运算  
**数组与标量之间的运算:作用于数组的每一个元素**

In [41]:
a.mean()

11.5

In [42]:
a = a/a.mean()
a

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

## Numpy一元函数  
**执行元素级运算**

In [43]:
a = np.arange(24).reshape((2,3,4))
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [44]:
a = np.sqrt(a)
a

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [45]:
np.modf(a)

(array([[[0.        , 0.        , 0.41421356, 0.73205081],
         [0.        , 0.23606798, 0.44948974, 0.64575131],
         [0.82842712, 0.        , 0.16227766, 0.31662479]],
 
        [[0.46410162, 0.60555128, 0.74165739, 0.87298335],
         [0.        , 0.12310563, 0.24264069, 0.35889894],
         [0.47213595, 0.58257569, 0.69041576, 0.79583152]]]),
 array([[[0., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 3., 3., 3.]],
 
        [[3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]))

## Numpy二元函数  

In [46]:
e,f = np.modf(a)
np.maximum(e,f)

array([[[0., 1., 1., 1.],
        [2., 2., 2., 2.],
        [2., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [47]:
f > e

array([[[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

# 数据的CSV文件存取  

In [48]:
a = np.arange(100).reshape((5,20))
np.savetxt("test1.csv",a,"%d"," ")
np.savetxt("test2.csv",a,"%.1f",",")

In [49]:
b = np.loadtxt("test2.csv",delimiter = ",")
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [50]:
b = np.loadtxt("test2.csv",dtype = int, delimiter = ",")
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

# 多维数据的存取  

In [51]:
a = np.arange(100).reshape((5,10,2))
a.tofile("test1.dat",sep=",",format = "%d")
a.tofile("test2.dat",format = "%d")

In [54]:
c = np.fromfile("test1.dat",sep=",",dtype=int)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
c = np.fromfile("test1.dat",sep=",",dtype=int).reshape(5,10,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [60]:
np.save("test.npy",a)
b = np.load("test.npy")
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

# Numpy的随机数函数

In [62]:
a = np.random.rand(3,4,5)
a

array([[[0.51716557, 0.052645  , 0.09782566, 0.07021669, 0.63966805],
        [0.77334663, 0.50652771, 0.01818029, 0.45568016, 0.78391498],
        [0.96089908, 0.31993519, 0.95555098, 0.83106625, 0.97970028],
        [0.78969634, 0.45581626, 0.95797968, 0.21336491, 0.47899566]],

       [[0.27914189, 0.59041128, 0.69695675, 0.60154715, 0.35641254],
        [0.93896266, 0.54527166, 0.31700705, 0.83268283, 0.95684248],
        [0.59909996, 0.54750845, 0.08965468, 0.53509944, 0.20919388],
        [0.33871019, 0.15744   , 0.35261731, 0.96206574, 0.98396723]],

       [[0.05647722, 0.36098614, 0.05920812, 0.34743331, 0.18305046],
        [0.61846279, 0.55541453, 0.80164747, 0.92391314, 0.23795098],
        [0.10651513, 0.99553145, 0.22507037, 0.27651792, 0.65664876],
        [0.25355219, 0.82236974, 0.20453887, 0.12704084, 0.60508362]]])

In [64]:
a = np.random.randn(3,4,5)
a

array([[[ 1.32972952,  0.55527837, -0.60745024, -0.73601236,
          1.68571494],
        [ 0.48241903,  1.91510207,  0.41432202,  0.98102431,
         -0.70609297],
        [ 0.01537031, -1.25756776, -0.35975195,  1.08198711,
          0.25100962],
        [-1.13495715, -0.0921335 ,  1.17382163, -0.73982071,
         -0.09294835]],

       [[-1.02593606,  2.05358316,  1.57273993,  1.75599622,
          1.25502748],
        [ 0.28326097,  0.31054413,  0.95212398,  1.93341774,
         -0.51507789],
        [ 0.30834157,  0.18303498,  0.47246338,  1.08366904,
         -0.27752926],
        [-0.10139992,  0.11232804, -1.54119461, -1.01347138,
         -1.01957192]],

       [[ 0.272536  , -1.5010248 , -0.45578086,  1.97311597,
         -2.22769524],
        [-1.5550204 , -0.3565685 ,  0.01553252,  0.79595394,
          0.64150377],
        [-0.16959437,  0.66543719, -0.21411752, -0.14770169,
         -0.04197337],
        [ 0.72003535,  2.09504282,  0.0576122 ,  1.59773714,
          0

In [66]:
b = np.random.randint(100,200,(3,4))
b

array([[196, 100, 161, 149],
       [148, 140, 100, 161],
       [153, 175, 117, 173]])

In [69]:
b = np.random.seed(10)
b = np.random.randint(100,200,(3,4))
b

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [70]:
b = np.random.seed(10)
b = np.random.randint(100,200,(3,4))
b

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [72]:
np.random.shuffle(b)
b

array([[173, 100, 140, 136],
       [189, 193, 129, 108],
       [109, 115, 164, 128]])

In [73]:
np.random.shuffle(b)
b

array([[189, 193, 129, 108],
       [173, 100, 140, 136],
       [109, 115, 164, 128]])

In [74]:
np.random.permutation(b)

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [75]:
b

array([[189, 193, 129, 108],
       [173, 100, 140, 136],
       [109, 115, 164, 128]])

In [77]:
u = np.random.uniform(0,10,(3,4))
u

array([[0.56444187, 7.65455818, 0.11788029, 6.11943341],
       [3.31882256, 5.59648365, 3.35499647, 4.11182546],
       [0.76855502, 8.5304299 , 4.39987456, 1.21954147]])

In [78]:
n = np.random.normal(10,5,(3,4))
n

array([[ 6.7101455 , 12.11056531, 13.12011669, 12.50820048],
       [14.20717363,  1.79875008, 15.29002579,  9.54107779],
       [ 6.37982703,  7.99769821, 12.22662292, 14.79969824]])

# Numpy的统计函数

In [83]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
np.sum(a)

105

In [86]:
np.mean(a,axis = 0)

array([5., 6., 7., 8., 9.])

In [87]:
np.mean(a,axis = 1)

array([ 2.,  7., 12.])

In [88]:
np.average(a,axis=0, weights = [10,5,1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

**\*加权平均：2\*10+7\*5+1\*12\/(10+5+1)=4.1875**  

In [89]:
np.std(a)

4.320493798938574

In [90]:
np.var(a)

18.666666666666668

In [93]:
b=np.arange(15,0,-1).reshape(3,5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [94]:
np.max(b)

15

In [96]:
np.argmax(b)

0

In [97]:
np.unravel_index(np.argmax(b),(3,5))

(0, 0)

In [98]:
np.ptp(b)

14

In [99]:
np.median(b)

8.0

# Numpy的梯度函数

In [104]:
a = np.random.randint(0,20,(5))
a

array([18,  3, 16, 18, 16])

In [105]:
np.gradient(a)

array([-15. ,  -1. ,   7.5,   0. ,  -2. ])

In [106]:
c = np.random.randint(0,50,(3,5))
c

array([[14, 15, 17, 25, 46],
       [48, 42, 17, 32, 17],
       [41, 16, 41, 26, 12]])

In [107]:
np.gradient(c)

[array([[ 34. ,  27. ,   0. ,   7. , -29. ],
        [ 13.5,   0.5,  12. ,   0.5, -17. ],
        [ -7. , -26. ,  24. ,  -6. ,  -5. ]]),
 array([[  1. ,   1.5,   5. ,  14.5,  21. ],
        [ -6. , -15.5,  -5. ,   0. , -15. ],
        [-25. ,   0. ,   5. , -14.5, -14. ]])]

**生成两个array数组，分别对应两个维度上的梯度**  